hall_light:

  input_boolean:
    autolight_hall_chandelier:
      name: "Вкл света коридор"
      icon: mdi:motion-sensor

  automation:
    - alias: Hall - Chandelier - On by motion
      trigger:
      - platform: state
        entity_id:
        - binary_sensor.ms_hall_occupancy
        - binary_sensor.ms_hall_door_occupancy
        from: "off"
        to: "on"
      condition:
      - condition: state
        entity_id: input_boolean.autolight_hall_chandelier
        state: "on"
      - condition: time
        after: "9:30:00"
        before: "21:00:00"
      action:
      - service: light.turn_on
        entity_id: light.chandelier_hall

    - alias: Hall - Chandelier - Off by no motion
      trigger:
      - platform: state
        entity_id:
        - binary_sensor.ms_hall_occupancy
        - binary_sensor.ms_hall_door_occupancy
        from: "on"
        to: "off"
      condition:
        condition: and
        conditions:
        - condition: state
          entity_id: input_boolean.autolight_hall_chandelier
          state: "on"
        - condition: state
          entity_id: 
          - binary_sensor.ms_hall_occupancy
          - binary_sensor.ms_hall_door_occupancy
          state: "off"
      action:
      - service: light.turn_off
        entity_id: light.chandelier_hall
