home_human_state_change:

  input_boolean:
    somebody_at_home:
      name: "Кто-то дома"
      initial: "on"

  timer:
    switch_hall_light_off_after_arrival:
      name: "Выключение света в коридоре через"
      restore: true

  automation:

    - alias: Change input_boolean.somebody_at_home to "on"
      trigger:
      - platform: state
        entity_id: &device_trackers
        - device_tracker.iphone_andrey
        - device_tracker.iphone_nastya
      action:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.somebody_at_home

    - alias: Change input_boolean.somebody_at_home to "off"
      trigger:
      - platform: state
        entity_id: *device_trackers
        to: 'not_home'
      condition:
      - condition: state
        entity_id: *device_trackers
        state: "not_home"
      action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.somebody_at_home

    - alias: Somebody arrived home - Turn on hall light
      trigger:
      - platform: state
        entity_id: person.andrei
        to: 'home'
      action:
      - service: switch.turn_on
        data:
          entity_id: switch.switch_hall
      - service: timer.start
        data:
          entity_id: timer.switch_hall_light_off_after_arrival
          duration: '00:05:00'

    - alias: Somebody arrived home - Restore home state
      trigger:
      - platform: state
        entity_id: input_boolean.somebody_at_home
        to: 'on'
      action:
      - service: scene.turn_on
        entity_id: scene.state_after_leaving_home

    - alias: Everybody left home
      trigger:
        - platform: state
          entity_id: input_boolean.somebody_at_home
          to: 'off'
      action:
      - service: notify.tg_chat
        data:
          title: "*Все ушли из дома*"
          message: "Всего вам хорошего"
      - service: scene.create
        data:
          scene_id: state_after_leaving_home
          snapshot_entities: &snapshot_entities
          - light.chandelier_bedroom
          - light.chandelier_hall
          - light.chandelier_kitchen
          - light.led_strip
          - light.balcony_left
          - light.balcony_right
          - light.bedside
          - light.bathroom
          - light.toilet
          - light.fontan
          - fan.humidifier
          - switch.kitchen
          - climate.split_sistema
      - service: homeassistant.turn_off
        entity_id: *snapshot_entities

    - alias: Turn off hall light after home arrival timer finished
      trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.switch_hall_light_off_after_arrival
      action:
      - choose:
          - conditions:
            - condition: state
              entity_id: binary_sensor.hall_motion
              state: "on"
            sequence:
            - service: timer.start
              data:
                entity_id: timer.switch_hall_light_off_after_arrival
                duration: '00:01:00'
        default:
        - service: switch.turn_off
          data:
            entity_id: switch.switch_hall
