kitchen_night_light:

  timer:

      # Отключает свет в кухне по завершении таймера
      kitchen_night_light_off:
        name: "Выключение ночника на кухне"
        duration: '00:01:00'
        restore: true

  input_boolean:

    # Позволяет контроллировать автоматическое включение и выключение ночника в кухне.
    autolight_kitchen_night_light:
      name: "Включение ночника кухня"
      icon: mdi:lightbulb-auto

  automation:

  - alias: Kitchen - Night light - On by door
    id: 'ktchn_nl_on_door'
    description: >
      Ночью включает свет после открытия двери в туалет или спальню.
    trigger:
    - platform: state
      entity_id:
      - binary_sensor.door_toilet_contact
      - binary_sensor.door_bedroom_contact
      from: "off"
      to: "on"
    condition:
    - condition: time
      after: '21:00:00'
      before: '09:00:00'
    - condition: state
      entity_id: input_boolean.autolight_kitchen_night_light
      state: "on"
    action:
    - service: timer.start
      entity_id: timer.kitchen_night_light_off

  - alias: Kitchen - Night light - On / Schedule off
    id: 'ktchn_nl_on_schd_off'
    description: >
      Включает свет или продляет таймер отложенного выключения, когда обнаруживается движение.
    trigger:
    - platform: state
      entity_id: binary_sensor.ms_kitchen_occupancy
    condition:
    - condition: state
      entity_id: binary_sensor.ms_kitchen_occupancy
      state: "on"
    - condition: numeric_state
      entity_id: sensor.ms_kitchen_illuminance_lux
      below: 12
    - condition: state
      entity_id: input_boolean.autolight_kitchen_night_light
      state: "on"
    action:
    - service: timer.start
      entity_id: timer.kitchen_night_light_off

  - alias: Kitchen - Night light - Off / Schedule off
    id: 'ktchn_nl_off_schdl_off'
    description: >
      Когда закончился таймер, выключается свет или откладывается выключение с перезапуском таймера.
      Свет остается включенным, когда есть движение на датчике и в комнате темно.
    trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.kitchen_night_light_off
    action:
    - choose:
      - conditions:
        - condition: state
          entity_id: binary_sensor.ms_kitchen_occupancy
          state: "on"
        - condition: numeric_state
          entity_id: sensor.ms_kitchen_illuminance_lux
          below: 12
        sequence:
        - service: timer.start
          entity_id: timer.kitchen_night_light_off
      default:
      - service: light.turn_off
        entity_id: light.hub

  - alias: Kitchen - Night light - On by timer
    id: 'ktchn_nl_on_by_timer'
    description: >
      Включает свет по запуску таймера.
    trigger:
    - platform: event
      event_type: timer.started
      event_data:
        entity_id: timer.kitchen_night_light_off
    condition:
    - condition: state
      entity_id: light.chandelier_kitchen
      state: "off"
    action:
    - service: light.turn_on
      entity_id: light.hub

  - alias: Kitchen - Night light - Sync with chandelier
    id: 'ktchn_nl_sync_chndlr'
    description: >
      Выключает ночник, когда была включена люстра.
      Включает ночник, когда ночью была выключена люстра.
    trigger:
    - platform: state
      entity_id: light.chandelier_kitchen
    condition:
    - condition: state
      entity_id: input_boolean.autolight_kitchen_night_light
      state: "on"
    action:
    - choose:
      - conditions:
        - condition: state
          entity_id: light.chandelier_kitchen
          state: "on"
        sequence:
        - service: light.turn_off
          entity_id: light.hub
      - conditions:
        - condition: state
          entity_id: light.chandelier_kitchen
          state: "off"
        - condition: time
          after: '21:00:00'
          before: '09:00:00'
        sequence:
        - service: timer.cancel
          entity_id: timer.kitchen_night_light_off
        - service: timer.start
          entity_id: timer.kitchen_night_light_off
