# Движение в доме
  - platform: template
    sensors:
      home_motion:
        friendly_name: "Движение в доме"
        device_class: motion
        value_template: >-
          {{ is_state('binary_sensor.ms_bathroom_occupancy', 'on')  
             or is_state('binary_sensor.ms_bedroom_occupancy', 'on')
             or is_state('binary_sensor.ms_bedside_occupancy', 'on')
             or is_state('binary_sensor.ms_hall_occupancy', 'on')
             or is_state('binary_sensor.ms_hall_door_occupancy', 'on')
             or is_state('binary_sensor.ms_kitchen_occupancy', 'on')
             or is_state('binary_sensor.ms_toilet_occupancy', 'on') }}

  - platform: template
    sensors:
      hall_motion:
        friendly_name: "Движение в коридоре"
        device_class: motion
        value_template: >-
          {{ is_state('binary_sensor.ms_hall_occupancy', 'on') or is_state('binary_sensor.ms_hall_door_occupancy', 'on') }}
